apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-data-cellranger-{{BUILDID}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{PVCSIZE}}Gi
  storageClassName: ssd
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cellranger-{{BUILDID}}
spec:
  template:
    metadata:
      labels:
        app: cellranger-{{BUILDID}}
    spec:
      initContainers:
      - name: cellranger-copydata
        image: asia.gcr.io/ts-uat/initcontainerimg:v1
        workingDir: /mounttest
        command: ["/bin/bash","-c"," gsutil cp -r {{CELLRANGERGCSBUCKET}} /mounttest/ && ls"]
        volumeMounts:
        - name: ssd-persistent-storage
          mountPath: /mounttest
        securityContext:
          privileged: true
      - name: cellranger-checkexistingfile
        image: asia.gcr.io/ts-uat/initcontainerimg:v1
        workingDir: /mounttest
        command: ["/bin/bash","-c"," rm -rf /mounttest/{{ID}}-{{BUILDID}}"]
        volumeMounts:
        - name: ssd-persistent-storage
          mountPath: /mounttest
        securityContext:
          privileged: true
      containers:
        - name: cellranger-cellranger
          image: asia.gcr.io/ts-uat/cellgsutil:v5
          workingDir: /mounttest
          command: ["/bin/sh"]
          args: ["-c", "sh /Cellrangerbash.sh {{BUILDID}} {{JENKINSJOBNAME}} {{EXPID}} {{ID}} {{TRANSCRIPTOME}} {{SAMPLE}} {{FASTQS}}"]
          volumeMounts:
          - name: ssd-persistent-storage
            mountPath: /mounttest
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      restartPolicy: Never
      volumes:
        - name: ssd-persistent-storage
          persistentVolumeClaim:
             claimName: ssd-data-cellranger-{{BUILDID}}
