apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-data-cellranger-{{BUILDID}}
  annotations: volume.beta.kubernetes.io/storage-class: "ssd"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{PVCSIZE}}Gi
  storageClassName: ssd
  -----------------------------------------------------------


apiVersion: batch/v1
kind: Job
metadata:
  name: cellranger-{{BUILDID}}
spec:
  template:
    metadata:
      labels:
        app: cellranger-{{BUILDID}}
    spec:
      initContainers:
      - name: celljobtest5-copydata
        image: asia.gcr.io/ts-uat/initcontainerimg:v1
        workingDir: /mounttest
        command: ["/bin/bash","-c","gsutil cp -r {{CELLRANGERGCSBUCKET}} /mounttest/ && ls "]
        volumeMounts:
        - name: ssd-persistent-storage
          mountPath: /mounttest
        securityContext:
          privileged: true
      containers:
        - name: celljobtest5-cellranger
          image: asia.gcr.io/ts-uat/cellgsutil:v2
          workingDir: /mounttest
          command: ["/bin/sh"]
          args: ["-c", "sh /mounttest/PUC_test/Cellrangerbash.sh {{BUILDID}} {{JENKINSJOBNAME}} {{ID}} {{TRANSCRIPTOME}} {{SAMPLE}} {{FASTQS}}"]
          volumeMounts:
          - name: ssd-persistent-storage
            mountPath: /mounttest
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      restartPolicy: Never
      volumes:
        - name: ssd-persistent-storage
          persistentVolumeClaim:
             claimName: ssd-data-cellranger-{{BUILDID}}
