apiVersion: batch/v1
kind: Job
metadata:
  name: seurat2-{{BUILDID}}
spec:
  template:
    metadata:
      labels:
        app: seuart2-{{BUILDID}}
    spec:
      containers:
        - name: seurat2job-seurat
          image: asia.gcr.io/ts-uat/seuratimg_conda:v2
          workingDir: /mounttest
          command: ["/bin/bash"]
          args: ["-c", "source ~/.bashrc; source activate py36; sh /mounttest/Taka/Scripts/Seurat2bash.sh {{BUILDID}} {{JENKINSJOBNAME}} /mounttest/{{RDSINPUTFOLDERPATH}} "]
          volumeMounts:
          - name: ssd-persistent-storage
            mountPath: /mounttest
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      restartPolicy: Never
      volumes:
        - name: ssd-persistent-storage
          persistentVolumeClaim:
             claimName: ssd-data

