apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssd-data-seurat-{{BUILDID}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{PVCSIZE}}Gi
  storageClassName: ssd
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{expidlower}}-seurat1-{{BUILDID}}
spec:
  template:
    metadata:
      labels:
        app: {{expidlower}}-seuart1-{{BUILDID}}
    spec:
      initContainers:
      - name: seurat1job-copydata
        image: asia.gcr.io/ts-uat/initcontainerimg:v1
        workingDir: /mounttest
        command: ["/bin/bash","-c","gsutil cp -r {{SEURATGCSBUCKET}} /mounttest/ && ls "]
        volumeMounts:
        - name: ssd-persistent-storage
          mountPath: /mounttest
        securityContext:
          privileged: true
      - name: seurat1job-checkexistingfile
        image: asia.gcr.io/ts-uat/initcontainerimg:v1
        workingDir: /mounttest
        command: ["/bin/bash","-c"," rm -rf /mounttest/{{ID}}_{{BUILDID}}"]
        volumeMounts:
        - name: ssd-persistent-storage
          mountPath: /mounttest
        securityContext:
          privileged: true
      containers:
        - name: seurat1job-seurat
          image: asia.gcr.io/ts-uat/seuratimg_conda:v2
          workingDir: /mounttest
          command: ["/bin/bash"]
          args: ["-c", "source ~/.bashrc; source activate py36; sh /mounttest/Taka/Scripts/Seurat1bash.sh {{BUILDID}} {{JENKINSJOBNAME}} /mounttest/{{ATCINPUTFOLDERPATH}} /mounttest/{{VTSINPUTFOLDERPATH}}"]
          volumeMounts:
          - name: ssd-persistent-storage
            mountPath: /mounttest
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
      restartPolicy: Never
      volumes:
        - name: ssd-persistent-storage
          persistentVolumeClaim:
             claimName: ssd-data-seurat-{{BUILDID}}
